# Site settings
title: Clean Blog
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://blogtest03.kalkinblog.tk"
twitter_username: kalkin_7
github_username:  
facebook_username: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]