# Site settings
title: kalkin7
email: your-email@yourdomain.com
description: "kalkin7's Blog"
baseurl: ""
url: "http://blogtest03.kalkinblog.tk"
twitter_username: kalkin_7
github_username:  
facebook_username: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]